# clap require rust 1.64.0 or higher at 2023-06-07
# https://github.com/clap-rs/clap/blob/v4.3.2/Cargo.toml#L17
image: "rust:1.64.0"

stages:
  - test
  - lint
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo

variables:
  CARGO_HOME: .cargo
before_script:
  - cargo fetch --locked

cargo-test:
  stage: test
  script:
    - cargo test

clippy:
  stage: lint
  script:
    - cargo clippy
rustfmt:
  stage: lint
  script:
    - cargo fmt --check

cargo-build:
  stage: build
  script:
    - cargo build
